// <auto-generated />
using AngularApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AngularApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularApp.Models.Links", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("LinkName")
                        .HasMaxLength(50);

                    b.Property<bool>("LinkStatus");

                    b.Property<string>("LinkValue")
                        .HasMaxLength(50);

                    b.Property<int?>("LinksId");

                    b.Property<DateTime>("UpdateDate");

                    b.HasKey("Id");

                    b.HasIndex("LinksId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("AngularApp.Models.Links", b =>
                {
                    b.HasOne("AngularApp.Models.Links")
                        .WithMany("Children")
                        .HasForeignKey("LinksId");
                });
#pragma warning restore 612, 618
        }
    }
}
